server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/match_engine?useUnicode=true&characterEncoding=utf-8
    username: root
    password: -hao19981208
    data:
      redis:
        host: localhost
        port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.qhy.pojo
  mapper-locations: classpath:*/*Mapper.xml
